### ISSUE TITLE
Bug: Smol time zone delay glitch

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1154]
### Who discovered this?

Em

### What happened?

A bug happened! Smol time zone glitch - If you’re in a time zone other than ET, and you hit the selection panel to select a different time zone, ET is checked.  [Video](https://drive.google.com/file/d/1it2p0crGQBmOauNKB7kogCJKToYmcJQx/view?usp=drive_link)
.

### Environment

staging

### What pages did this appear on?

User Profile

### Detail the steps for someone to reproduce

Pre selected item should match whichever time zone is currently selected

### What browsers are you seeing the problem on?

Chrome

**Comment by jonathanbobel** [comment]
Hi. Removed the default but the way the code is structured it doesn't appear we're able to set the default as the current selection. Additionally, the [UK Design System](https://design-system.service.gov.uk/components/radios/) specifically calls out to not have a default selection, so that might have something to do with it.
