### ISSUE TITLE
Bug: UI delivery status tables say messages were delivered `right now`, perpetually

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#1159]
### Who discovered this?

Tim Lowden

### What happened?

I just looked at messages I have sent in the Batched Jobs table, and they all say they were sent right now (they were all sent hours earlier):

![Image](https://github.com/GSA/notifications-admin/assets/6556888/e8e61c89-da13-43c4-ac7f-2d4d51021fa7)

This affects everywhere in the UI I can see a time of delivery, including main dashboard recent batch table, individual batch dashboard pages, and delivered messages dash. It **does not** affect the time of send in the downloadable reports, that I can see.

### Environment

staging

### What pages did this appear on?

https://notify-staging.app.cloud.gov/services/e50562b8-43f6-4063-99cb-f5ab43993b8c/jobs/1c9b4056-dd8c-4f3f-b1b9-e428e6c0ab66

https://notify-staging.app.cloud.gov/services/e50562b8-43f6-4063-99cb-f5ab43993b8c/notifications/sms?status=sending,delivered,failed

### Detail the steps for someone to reproduce

Log-in, choose a service, and view main dashboard `Recent Batches` table or any other table where the date/time of send is present.

### What browsers are you seeing the problem on?

Chrome

**Comment by heyitsmebev** [comment]
Thanks to @A-Shumway42, what we uncovered is that there's something funky about the "status" and how time is being updated. 
When status is **sending**, it's using created_at, which is the timestamp of when it was created
When status is **delivered**, the time is then updated. The problem is that it keeps updating...

A separate PR will fix the UI Time Sent column but for other timestamps throughout the app, seems more backend related to status.

**Comment by tdlowden** [comment]
For reference, it looks like this is not happening in `prod` right now, only in `staging`. Here is a `prod` screenshot:



![Image](https://github.com/GSA/notifications-admin/assets/6556888/4662cf4b-ad3c-4c69-a39a-2cec6f272c52)
