### ISSUE TITLE
Bug: Norfolk Batches table repeats one batch

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1189]
### What happened?

A bug happened! Norfolk sent a batch of messages. This batch is now repeated 5 times in the batches table.

![Image](https://github.com/GSA/notifications-admin/assets/91496588/4483bd81-5569-4370-8044-91621f70bcf4)

### Environment

production

### What pages did this appear on?

Dashboard

### Detail the steps for someone to reproduce

If only one batch is sent, show only one row of data.

### What browsers are you seeing the problem on?

Chrome

**Comment by tdlowden** [comment]
See https://gsa-tts.slack.com/archives/C0107UC0W1M/p1707491284170599?thread_ts=1707487796.554849&cid=C0107UC0W1M for more

**Comment by heyitsmebev** [comment]
I set up a PR to fix the issue. https://github.com/GSA/notifications-admin/pull/1203

- The issue seems to be connected to the relationship between jobs and notifications. 
- There can be many notifications but one job_id in a given csv job upload. Example, if there's 50 rows in an upload, there would be 50 notifications but one job. Each row is a notification 

I fixed this issue by aggregating notifications that share the same job.
