### ISSUE TITLE
Get partner feedback on Notify logo proposal

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#1214]
We should design and perform a very lightweight research activity to get some feedback from existing partners on our proposed brand and logo.

Questions to answer:
- Does the proposal make sense to partners?
- How would they describe the proposal?

**Comment by em-herrick** [comment]
I have not seen the proposal, just the logo can you link here @stvnrlly ?

We did show the logo to Norfolk, they didn't get it and weren't sure about the bell icon, preferring a speech bubble or something else. I am sharing this because I am wondering what we can do with feedback of this sort from partners given the state we're in with TTS approvals.

**Comment by stvnrlly** [comment]
Yes, this is a part of the approvals process. I'll follow up with some more info.
