### ISSUE TITLE
Generate a way to export all Notify.gov user contact information

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1218]
As we communicate to users upcoming changes, specifically related to Login.gov roll out it would be really helpful if we could create a CSV/excel export (or any way to display) a list of every Notify.gov user.

Ideally this list would include:
- user's name
- email
- phone number
- service they are a member of

I hoping we can start with a quick MVP of this process for the Login.gov roll out, but we could refine this over time as we think more strategically about Notify.gov emails to users with new feature releases.

## Implementation Sketch and Acceptance Criteria

- [ ] Add a new page, section, or link somewhere in the platform admin section of the admin site to retrieve the result of the new API endpoint created in https://github.com/GSA/notifications-api/pull/1078
- [ ] The new page likely needs to be wired up to a view that both checks for platform admin access and consumes the endpoint and converts the JSON output to a CSV to be downloaded; structure the CSV based on this list of fields:
   - [ ] user's name
   - [ ] email
   - [ ] phone number
   - [ ] service they are a member of
- [ ] Generate the CSV on the fly in the view and return it as a direct response to the browser
   - If you aren't sure how to do this, [this GeeksforGeeks article](https://www.geeksforgeeks.org/how-to-create-csv-output-in-flask/) explains how to do this with Flask very nicely!  Pay close attention to the `download_csv` method.
- [ ] Add tests
- [ ] Add documentation as needed, either [in our docs (found in the API repo)](https://github.com/GSA/notifications-api/blob/main/docs/all.md) and/or as additional content to be added in the platform admin page directly

## Security Considerations

- **Only** platform admins should have access to this feature, as it contains some of our system's user information.
- The output should not be stored anywhere permanently.
   - Downloading the information directly to the GFE of an authorized staff member (platform admin) is the only exception, and in that case we would need to follow agency and federal guidelines on data retention.

**Comment by em-herrick** [comment]
@ccostino added an issue here, as discussed in UX weekly on 2/14. A bit of urgency in deciding if this is something we can/want to prioritize for Login.gov roll out against other dev work. Really not sure how much of a lift this will be!

**Comment by terrazoon** [comment]
I'm going to start with an assumption that users will never do this (because they don't have the right to access PII of other users, particularly users in other services).   And I"m going to further assume the purpose of this ticket is that we don't have direct access to the database on production.

So I assume it would be acceptable for this to be a command.

**Comment by ccostino** [comment]
@terrazoon that's right, this is a platform admin-only function as it's getting contact info for the Notify.gov users themselves, not the folks that notifications are being sent to.  Also correct that this is due to having lack of direct access to the database!

As far as it being a command though - I'm assuming here you mean a Flask command - that's tricky, because the output can't go to `STDOUT` and would need to be stored somewhere, most likely one of the S3 buckets, and then we'd need a way to get to it.

What we need is another page/action in the Platform Admin interface in the admin app that let's only platform admins do an export of users in the system.  This way we're providing our team with the means of taking care of itself without direct engineering support, and the CSV output would be generated to be saved directly on the user's machine.  That of course has its own privacy implications, so there's likely a bit more that has to be considered here before we can start full work on this.

@stvnrlly, am I missing anything from a compliance side with this, given what I described above?

**Comment by terrazoon** [comment]
I will make this a daily task.  Backend will get the users and upload a fresh csv every night.  Then front end can just have a button to download the latest csv.

**Comment by ccostino** [comment]
https://github.com/GSA/notifications-api/pull/1078 adds the API support to do this and provides a new endpoint that returns a JSON response with the user information.

We now need a frontend piece in the admin to consume the endpoint and handle the JSON response.  This would be something in the platform admin section of the site, and likely just convert the JSON response to a CSV for the platform admin to download.

**Comment by terrazoon** [comment]
I added the UI portion as well:  https://github.com/GSA/notifications-admin/pull/1815
