### ISSUE TITLE
Bug: Norfolk large file error

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1222]
### Who discovered this?

Tiffany, Norfolk Sender

### What happened?

A bug happened! I am not sure if this is a bug. But our Norfolk sending staff tried to upload a spread sheet of 350 phone numbers and got an error that it was too large. She ended up sending it to support staff to export as a CSV and then the file was small enough to upload.

See screenshot they sent us:

![Image](https://github.com/GSA/notifications-admin/assets/91496588/5e9faa0b-8405-4073-bdba-825dd4cb58c4)

### Environment

production

### What pages did this appear on?

Batch list upload screen

### Detail the steps for someone to reproduce

- [ ] #1237
- [x] Discuss and decide if we need to change the upper limit threshold 

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by ccostino** [comment]
@em-herrick, do you happen to have at least an approximate date/time this happened for the user?  This will help when looking through the logs to see the error(s) that were thrown to narrow down what the issue is.  To that end...

Things to check for here for potential causes:

- Log entries at the time of the upload
- Any app config settings on file size limits
- Any limit checks or error handling in the CSV upload code itself
- [cloud.gov S3 settings that might impact file size uploads](https://cloud.gov/docs/services/s3/)

**Comment by em-herrick** [comment]
Yes, I was also surprised, with such little data... Tiffany said she scheduled/uploaded on Wed the 14th for a 15th send.

**Comment by terrazoon** [comment]
It sounds like the scope for this is just the UI aspect to make the error match our style.

As for the size limit, it's appropriate.  Clearly this was a user error of some sort and they were not uploading a plain csv file.  It's quite likely that if did not have a size limit, we still would have been unable to process whatever they uploaded, because the file format would have been wrong.

**Comment by em-herrick** [comment]
Yeah I agree with ken here.

I'd like to include in the UI error message some instructions: If the file is to large (excel) try converting to CSV.

(which is how Norfolk solved this)

**Comment by em-herrick** [comment]
Created a new issue for UI change. Closing issue.
