### ISSUE TITLE
Base template: <footer>

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#1259]
In creating a new base template, we want to draw on general best practices along with specific TTS examples.

To complete:
- [x] Research `<footer>` elements
- [x] Propose the contents of the tag for team discussion

**Comment by heyitsmebev** [comment]
After looking into it, I've realized that the `useFooter` macro might be more of an overkill than what we actually need for our setup. It introduces additional complexity and requires more files and configurations than are truly necessary. Right now, we're only using it in the `admin_template` and the `main_template`, and it doesn't provide the level of reusability that would justify its complexity and extra work.

In the current setup, `useFooter` is invoked in the `admin_template`, where it passes parameters, but this level of customization isn't utilized broadly across our project. 

To simplify our footer, I have created a `footer.html` file within the components directory and when we are ready, we can delete the macro `(components/components/footer)`. The new `footer.html` file contains all necessary links and can be easily included in our templates. With the new `base.html`, the need to call the footer from multiple places is eliminated, because both the main_template and admin_template will extend from base.html. This change should cut down the clutter and provide more clarity. 

To include the new footer component, we can simply use `{% include "new/components/footer/footer.html" %}` in the base.html file.
