### ISSUE TITLE
Create a public github READ ME

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#142]

**Comment by tdlowden** [comment]
Adding the github repo question to ur Core 4 sync agenda

**Comment by tdlowden** [comment]
Steven has begun work on this, and Tim has requested Mac admin access in order to be able to use pandoc for markdown conversions.

**Comment by em-herrick** [comment]
Oh great, would we consider this to be public? Even if its on a password demo?

**Comment by tdlowden** [comment]
Even thought the ability to send is delegated to signed-in users, the documentation is just out there for people to read at https://notify-demo.app.cloud.gov/. It's technically public. It also exists in GH, albeit in the content template form rather than a README. But I would say this meets our definition of "public"

**Comment by em-herrick** [comment]
works for me! We also should be getting the blog post up soon, with similar information. :)

**Comment by tdlowden** [comment]
perfect. moving to close
