### ISSUE TITLE
User Story: Remove email and password in user settings after login.gov integration

### ISSUE THREAD

**Issue by jonathanbobel** [GSA/notifications-admin#1427]
### As a [type of user],

Text Sender

### I want [an action or feature],

To only have my email and password available to change on Login.gov

### So that [benefit or value].

The notify application no longer has to handle keeping track of email and password since we're using login.gov to handle this functionality 

### Detailed condition or criteria that must be met for the user story to be considered complete.

- Remove email and password from settings page

### List of specific tasks or sub-tasks that need to be done to implement the user story.

- [ ] Remove email and password from settings page

**Comment by jskinne3** [comment]
I am not totally sure what is meant by _the settings page_.

I looked under User profile as a likely place for a password change feature. I found I was unable to test this because there are a couple links there:

![Screenshot 2024-04-17 at 9 35 20 AM](https://github.com/GSA/notifications-admin/assets/546123/ca5efef8-fb6c-45a7-bfb9-b294c2bfb729)

**Comment by em-herrick** [comment]
@jskinne3 thanks for flagging! Carlo and I talked about next steps here. I am going to close this issue in favor of a new one that will work to resolve these glitches.
