### ISSUE TITLE
Improve logging in the user sign-in flow

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-admin#1505]
As we've been investigating residual issues with the Login.gov integration, we've noticed that our logging for the process isn't ideal and could be improved.  There are some log entries that either should not be there or at least need to be adjusted as they contain more information than is necessary, and we need to add some statements in other parts of the process where we're reaching out or expecting a response from an external service.

Better and more accurate logging in the entire sign-in flow will greatly improve our ability to troubleshoot issues.

## Implementation Sketch and Acceptance Criteria

- [ ] We need to adjust [this logging statement when retrieving a user from the API](https://github.com/GSA/notifications-admin/blob/main/app/notify_client/user_api_client.py#L43):
   - It might still be helpful to have a statement here so we know that a user is being retrieved and we can correlate that with a timestamp, but we should at least mask the email address before the `@` symbol.

For the remainder of the entire sign-in flow, think about the entry and exit points in and out of the method and all of the integration points with our own API and Login.gov.  As different branches of logic are being reached or external services are being called, these are good spots for log entries that give a clear indication of what is about to happen or what just happened.

Think about the information you need to see as you're debugging this yourself locally and what would be useful in the event of a production issue that we need to investigate.  These are good candidates for sensible log statements.  Other pieces of information that would be helpful in correlating a sign-in event with timestamps will also be useful.

Lastly, there might be an opportunity here in improving how we format our logs.  While that's beyond the scope of this issue, if there are ideas you have and ways you can make strides toward improvements in that capacity, think about that as well and jot down any notes here so that we can incorporate them in some future work to improve overall application logging.

- [ ] Add more logging statements that help increase our visibility into what the application is doing and when third party services are being interacted with without exposing any sensitive information (e.g., PII, credentials, unique keys, etc.).
- [ ] As you add logging statements, run through the process locally to test and see that you're getting better visibility into the application behavior while it's running and that it matches your understanding of what the code is doing as well.
- [ ] Make log formatter adjustments as necessary but only in support of this work directly; make notes for any broader improvements here so we can leverage them in future log improvement efforts.

## Security Considerations

- There is a trade-off here between how much information we can log and share vs. what we need to not expose.  That said, we ought to be able to still help ourselves much more without logging sensitive information.
- Robust and informative logs go a long way in making it easier to troubleshoot application issues and respond to security incidents.

**Comment by terrazoon** [comment]
The problem is "what to do for production"

1. On production we only have access to logs
2. We are not allowed to expose the email address (even a partially masked one)

So if user X says "I can't log in", how are we supposed to search in production?   I guess we can search for errors messages, but we don't need to add logging for that.  But there's no way to tie a particular error message back to a particular user.

Even those the User object has an id, we don't know what those ids are and can't map them easily to any particular user.


@ccostino and @stvnrlly what about this?

1. We make a command get-user-id-for-email-address, where we submit a user's email address to that command and get back the user id.
2. Then we enhance the logging around sign-in, using the user id.


That way an investigator could get the user's email address from Em or from the user, run this command, get the user id ... and then search the logs for everywhere this user id pops up (hopefully just in specialized sign-in logs).

**Comment by terrazoon** [comment]
Proposal:

1. Write a command that dumps the information for a given user from the db based on an email address.  This includes the user_id.
2. Add debug messages that incorporate the user_id at various stages through the sign in process where things could go wrong.  Have all these messages include the tag #notify-admin-1505 so it easy to find all of them at once.

**Comment by terrazoon** [comment]
https://github.com/GSA/notifications-api/pull/1206
