### ISSUE TITLE
Visualization tools: A recent activity bar chart that displays the total messages allowance

### ISSUE THREAD

**Issue by jonathanbobel** [GSA/notifications-admin#1544]
As part of the larger redesign, create a display that reflects the total messages sent.

- [x]  The user should be able to view a chart that represents the total message allowance
- [x]  The chart should automatically update as messages are sent
- [x] Connect the frontend UI with backend API endpoints 

![Image](https://github.com/GSA/notifications-admin/assets/1233986/267892cc-06ff-4a52-a3b3-212229f1d521)

**Comment by heyitsmebev** [comment]
@jonathanbobel 

Check out this branch [socketIO](https://github.com/GSA/notifications-admin/pull/1558/commits/01321aeddc3926b0454837e2464d495830ea65e9#diff-28ffa30d4d329c43ee64a275a90f52c0b9cdf3403d1bdd1e4664efbc5bd289bb). I have connected the web socketIO (so that we can pull in real data without having the user refresh the browser) to our API. In this branch, you can see how the data can be used and pulled into Chartjs.

You'll need to checkout to 1006 branch in the API repo.  In the services_dao.py file, under dao_fetch_stats_for_service_from_day, change the NotificationHistory to Notification. You should be able to pull in data by doing that.

Oh and install flask-socketIO using this command in you local admin pip install flask-socketio  
(https://gsa-tts.slack.com/archives/D066BEVQG95/p1717129608638079)
I think that covers everything to get you started on the data/chartjs
