### ISSUE TITLE
Check with ISSO to see if we can take a different approach to PII (for the sake of reporting robustness)

### ISSUE THREAD

**Issue by ecayer** [GSA/notifications-admin#1838]
Today it's causing problems not to be able to retain the phone number and incorporate it into reports. Now that we know it's causing problems, we need to check again on what the requirements are here and see if we can take a different approach.

**Comment by ecayer** [comment]
Can we also document all the rejected options for incorporating phone numbers into reports, why they were rejected, and when/if we should check in on them again for viability?

**Comment by terrazoon** [comment]
We thought this was going to be necessary due to the problems inherent in using ExpiringDict as a cache, which meant we needed a separate cache for each worker, and sometimes users would get stuck as report generation would transition to a new worker with no cache -- hence inability to retrieve reports.

However, flask does allow shared memory across workers in the form of multiprocessing.Manager().  So now the cache is generated once at startup, then periodically refreshed every 30 minutes.   So there is no need for redis, and no reason to try to get permission to use redis.
