### ISSUE TITLE
Activity Page: Recent job reports not displaying (for some one-off sends)

### ISSUE THREAD

**Issue by em-herrick** [GSA/notifications-admin#1859]
Some jobs on Washinton's service even when sent less than 7-days ago are not displaying as downloadable on the All Activity table. (Screen shot shows a message sent yesterday, 8/15, as n/a).

![Image](https://github.com/user-attachments/assets/aae360c2-23cd-4df5-a4eb-29c4b026552d)

This only seems to be the case on Washington's service. @em-herrick can provide an invite to their service as needed to investigate.

**Comment by heyitsmebev** [comment]
I updated the UI conditionals to ensure that "N/A" shows up after 7 days.
https://github.com/GSA/notifications-admin/pull/1864

However, this ticket requires the attention of a backend engineer to verify that the job exists and that the `created_at` timestamp is correctly recorded.

The issue at hand involves the display of the download button, which is dependent on the availability of the job's data. The [get_time_left](https://github.com/GSA/notifications-admin/blob/5a3f3e5ca00090457f67892fc9b19e6d71e3caa3/app/formatters.py#L417) function calculates the time left based on the created_at timestamp. If the data retention period has passed, this function returns "Data no longer available," causing the table to display "N/A" instead of the download link, which would otherwise call view_job_csv.

We need to ensure that the created_at timestamp for the job is accurate and consistent.

In this example, two jobs appears to be processed around the same time, but check to see if created_at is accurate. 
![image](https://github.com/user-attachments/assets/93f9dcb3-b86c-49fa-a161-02034723bb6a)

A while back, there was this ticket created related to created_at not being accurate. It could be related: https://github.com/GSA/notifications-api/issues/1199

**Comment by heyitsmebev** [comment]
https://github.com/GSA/notifications-api/pull/1284 (possible fix to created_at issue)

**Comment by heyitsmebev** [comment]
@em-herrick 

It looks like the issue may be resolved with @terrazoon's [PR](https://github.com/GSA/notifications-api/pull/1284), which ensures the **created_at** timestamp is accurate. However, if this PR did indeed fix the issue, we still cannot change the timestamps for past jobs in the database. As a result, the download CSV file that were missing on the Activity page may exceed the 7-day limit, making that data unavailable to users.

**Comment by em-herrick** [comment]
@heyitsmebev thanks for the flag. I didn't check the time-based reports, and wonder if these jobs show up in the there, i assume they are because we haven't heard otherwise from partners. 

To clarify, this issue wasn't surfaced from a partner directly, I found it as I was clicking through the WA service. So i think that it will be okay if we've fixed this for future jobs :)

**Comment by ccostino** [comment]
This has now been taken care of!
