### ISSUE TITLE
Low Contrast in Edit Text Template

### ISSUE THREAD

**Issue by sheevdave** [GSA/notifications-admin#2080]
![Image](https://github.com/user-attachments/assets/1d5ab577-cd50-4d2c-8263-be6f4ef3f965)

**Comment by heyitsmebev** [comment]
I noticed the contrast issue flagged by the WAVE tool on the text element is a false positive. The element has aria-hidden="true", so it’s not meant to be read by screen readers or flagged for contrast accessibility. WAVE seems to be picking up on this invisible layer. Because of the layering and aria-hidden, this contrast does not actually need adjustment.
