### ISSUE TITLE
Draft workshop agenda for Aspen Summit

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#259]
Planning doc is here: https://docs.google.com/document/d/1pj14__Z3vyiByek3dmfUjBKSPSYxBI3XOdVct97M9Ng/edit#

Agenda Mural is here: https://app.mural.co/t/gsa6/m/gsa6/1671215720068/fb11460b98c988d6974337d6a2967873fdcf5f3e

**Comment by em-herrick** [comment]
Made some progress on developing a series of Operationalizing Notification journey maps. Thinking these journeys will ground the majority of our session. 

To do in Jan:

- [ ] @em-herrick to distill roles involved into persona framework (to use in session)
- [ ] Review this journey map framework as a team: what parts should we iterate / clarify more?
- [ ] Align on type of feedback we want on these journeys + if we will have the right people in the room 
- [ ] create mechanics for facilitation on getting feedback on these journeys
- [ ] Develop rest of agenda (including when to introduce notify and how we want to surface patterns/themes across journeys)

 @amyashida reviewing these journey maps is another nice to have for your solo week in Dec. Specifically since you'll be in the room facilitating! Some questions:

- Does this framework make sense? Too in the weeds for this audience?
- How might we start to think through mechanics (documenting, facilitating etc)?

**Comment by tdlowden** [comment]
@em-herrick i think #273 might be complete? is #274 still something we are looking to do, or no?
