### ISSUE TITLE
Scope using the 2FA send code feature to confirm consent on websites

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#317]
On multiple interviews, we have heard a desire for partners to add a "sign up for updates via text" action on their website. If there is a possibility to confirm phone number via a code or even auto-send a message that says something like "you have subscribed to Vote.gov notifications by text, if you do not wish to receive these messages, please reply STOP", it would allow us to work with partners to collect consent directly from their site.

**Comment by tdlowden** [comment]
I feel like this could be a way to repurpose the homegrown auth we have after the move to login.gov? Still needs scoping.

**Comment by VRagulina** [comment]
Wisconsin has been asking about. Need more reserach

**Comment by terrazoon** [comment]
@stvnrlly @ccostino 

What is the ask here?

1. An agency puts a link on their website telling users to subscribe for agency updates via text.
2. User provides phone number
3. Agency sends request to us with phone number
4. We send verify code
5. User verifies
6. We respond "yes they verified"
7. Agency .... adds user to their csv file??

**Comment by terrazoon** [comment]
Feedback from @stvnrlly 

yeah, tim had found a how-to guide in an amazon blog post or something about how a form on a site could trigger an sns action. i think he was also looking for product offerings that'd more directly handle consent management for our partners
based on how notify has progressed since then, i think this would be out of scope for us (but something that a partner could set up once we offer api access)



Closing as out of scope, will not do.
