### ISSUE TITLE
Scope integrating with login.gov for all authentication

### ISSUE THREAD

**Issue by rahearn** [GSA/notifications-admin#338]
Need to figure out how much work it would be to implement login.gov authentication in place of existing username/password

It will make LATO easier if we can do it, and some sort of federated login might be a complete blocker for the full ATO.

Output of this story:

- [x] relative level of effort to replace username/password/sms with login.gov
- [x] decide on where in the roadmap that work can slot in.

**Comment by tdlowden** [comment]
Steps to integration:

- [ ] Obtain access to sandbox
- [ ] Configure in sandbox
- [ ] Mod SOL IAA
- [ ] Implement in prod

**Comment by terrazoon** [comment]
I downloaded their sample app (written in ruby) and am going through it.

**Comment by terrazoon** [comment]
The sample app (identity-oidc-sinatra) does not seem super useful.

I think the steps forward are:

1. Create an account at login.gov and a test app that points to our staging.   See:  https://developers.login.gov/testing/
2. Put a login.gov button on our app that only appears in staging.  Make sure any responses or errors from clicking on this button get dumped to the log
3. Iterate -- on staging.  We have to use staging because we have to provide a stable URL for login.gov to redirect to


Although we have agreed on OIDC as opposed to SAML, it still seems like we have to select some level of strictness.  There are very options like `phishing_resistant=true` and some levels (0,1,2,3) I don't understand yet.  Some levels seem to require SSN, we probably don't want that.

We also need somewhere to store our public/private key.    And also when login.gov returns a UUID for the user, how to manage that?   It sounds like this UUID will not change, so should we put it in the database in the users table?

**Comment by rahearn** [comment]
FWIW, I'm 99% sure that for sandbox a redirect URL of `http://localhost:3000/my/path` is valid, so you can debug in dev.

**Comment by terrazoon** [comment]
Work We Can Start:

1. Create account and test app at login.gov that points to staging
2. Put login.gov button on sign-in page that only appears on staging
3. Find a home for our public/private key
4. Modify the users table in the db to support a user login.gov UUID?

Open Questions:

1. When we get the user UUID back from login.gov, do we put the UUID in the session?  Do we check it on every page load?  Or do we just set the current_user to whoever has that UUID and let the app run as it ran. before?   Login.gov is supposed only for authentication so once we get the UUID back, it is done.

2. What level of strictness do we want?  The sample app shows IAL 1 & 2, LOA 1 & 3, AAL 2, AAL 2 phishing resistant, and AAL 2 with hspd_12 = true.

**Comment by terrazoon** [comment]
There are a lot of unknowns for this so I will just estimate 21 days of work.  And we should start immediately, of course.

**Comment by terrazoon** [comment]
Answers to my questions from Steven:


1. we should spend a short bit of time trying to get the sandbox working, as that's perfect for this. if we can't, we can actually set up a new environment since this'll be a longer-running process and is worth the small cost. local dev theoretically should also work
2. secrets can go in github secrets. there's some info in the docs about how these get into the deployment, and then we can update our local setup script to pull the creds for the .env file
3. we'll want ial1
4. we can believe login and put the data right into current_user

**Comment by terrazoon** [comment]
Some questions:

1.  When we log in with login.gov, we stay logged in for some period of time (an hour)?  If a user clicks 'logout' in our app, they are not really logged out during that our and if they go back to our will see that they remain logged in.  Should we therefore logout at login.gov, terminating that session, when the user clicks logout in our app?  I assume the answer is yes, but this does mean that the user will get redirected to login.gov, have to click logout again there, and only then will they be redirected back to our app in the logged out state.

2. Is login.gov going to replace our existing mechanism, or provide an alternate login path?
