### ISSUE TITLE
Explore what languages/characters AWS supports vs what is enforced in the app

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#409]
Currently, some special characters cause the message count to jump, and many characters from other languages are not supported at all. It seems like this is something that was coded into the system based on UK carriers. Do we need to adjust or remove this code?

- [ ] What is possible in AWS SNS in terms of character support
- [ ] Do some special characters actually "cost" more in AWS?
- [ ] Adjust the app code to allow for maximum language support AWS provides

**Comment by tdlowden** [comment]
This appears to be a result of GSM encoding. SNS has a default of 160 GSM chars 

https://support.dotdigital.com/hc/en-gb/articles/4402059309202-The-GSM-Character-Set#:~:text=GSM%2C%20or%20Global%20System%20for,alphabet%20defined%20by%20GSM%203.38.

https://docs.aws.amazon.com/sns/latest/api/API_Publish.html

**Comment by tdlowden** [comment]
SNS specific info here: https://docs.aws.amazon.com/sns/latest/dg/channels-sms-best-practices.html#channels-sms-best-practices-limits:~:text=User%20Guide.-,SMS%20character%20limits%20in%20Amazon%20SNS,-A%20single%20SMS

They use an example in Chinese, so... one would think those characters are supported

**Comment by terrazoon** [comment]
I believe SNS supports anything.  They have a few restricted countries you cannot send to, but I don't think there are any language restrictions.

The app itself seems to limit to latin-based languages.  I was able to send Spanish, German, and Italian messages and they all appeared correctly on my phone.   The code also explicitly supports Welsh by allowing for some Welsh diacritic marks.

**Comment by terrazoon** [comment]
In the Chinese example above, it states that the characters are all non-GSM characters so the text message will count as two messages instead of one, so it seems clear that going beyond the GSM set will cost more money.

**Comment by terrazoon** [comment]
There is one call to an OnlySMSCharacters validator that can easily be commented out, which makes it possible to to save templates with non-GSM characters and then send SMS messages based on those templates.  However, in doing so and in sending myself a Korean message, I did in fact receive "?? ?? ?????? ???? ????" because my phone doesn't have the Korean character set for text messages (or I haven't set my text preferences, or something).

The error message when saving says "You can't use these characters because not all phones will display them properly".  So do we want to support Russian, Chinese, Korean, Arabic, etc?  How can a platform admin know the phone would support it?  Or would they always double send in the target language and English?

This change looks like it is easy to make, but do we want to do it now or say "for the trial we are support these five languages" etc. and think about it some more?

**Comment by tdlowden** [comment]
This is super helpful, thanks! I guess this points to a situation where if a sender knew that a recipient had a language preference that was non-GSM, they could make a hypothesis that the phone would accurately depict the characters. BUT, absent that knowledge, I think the guardrails the UK used with regard to the error message about display seem well-founded. 

I am assuming this is an all-or-nothing global setting?

**Comment by terrazoon** [comment]
Yes, right now it's all or nothing.  When you push 'save' on the template it runs everything through a validator.

**Comment by tdlowden** [comment]
cc @stvnrlly and @ccostino for opinions. I think we could afford to leave this as-is for the moment. Feels like in the future, we may want to *allow* for other character sets, but we may need to add documentation that warns users they may not appear on phones correctly?

**Comment by tdlowden** [comment]
Moving to close and re-assess in the future
