### ISSUE TITLE
Document what the Priority Queue does

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#425]

**Comment by terrazoon** [comment]
At first glance, it looks like it works like so:

1. UK Notify has two sms providers (mmg and firetext, both British companies).   In config.py, mmg is given a priority of 51 and firetext 49, initially.
2. Templates can specify (somewhere?) that an SMS message is a priority message, which will cause the sms message to be put in the priority queue, which means it will go to the current "priority provider".  Initially this will be mmg, but whenever an exception occurs, points are taken away from the provider it happens to and reassigned to the provider that did not have an exception.

For our purposes, therefore, it seems like priority queue doesn't do anything.  We have replaced the 51/49 split between mmg and firettext with a 100% allocation to SNS.

The commentary about this priority feature is not 100% complimentary if you look here:

https://news.ycombinator.com/item?id=22778309

The consensus seems to be that the original team basically reinvented the load balancer.

**Comment by terrazoon** [comment]
When you create a template, you are given the choice to use the Priority Queue or no.  We should probably add some text that Priority Queue should be reserved for truly high priority or something like that.  Otherwise, as noted in the documentation, if someone puts everything in the priority queue it will be slower than the regular queue.  They are, under the hood, just queue 1 and queue 2.

**Comment by tdlowden** [comment]
@stvnrlly @ccostino wondering your thoughts on if we should take any action here? I feel like priority queue can prove valuable in specific situations, but it seems like it should be something only a platform admin could enable. Otherwise, why would we allow any partner to attempt to have their messages take precedent? and if they all happened to choose priority queue, then it ends up performing as the default queue

**Comment by tdlowden** [comment]
That's ok by me to leave as-is currently, but do we still surface the priority queue option to users?

**Comment by terrazoon** [comment]
I think if we leave it as is, we should hide it in the UI because it's currently not a priority queue.  A priority queue should work like:

1.  Check if there is anything in the priority queue.  Work on that queue till it's empty
2.  Work on regular queue but periodically check the priority queue and go back to #1 etc.

**Comment by ccostino** [comment]
Yup, I agree with @terrazoon - this shouldn't be surfaced to users.

**Comment by tdlowden** [comment]
✔  adding #552 

Closing this. Thanks @terrazoon

**Comment by terrazoon** [comment]
I saw this in the UI once.  I think you see it when you create a new template.  Right now that functionality is not working, so I can't confirm.
