### ISSUE TITLE
Research and document the capabilities and purpose of `Research Mode`

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#466]
Do we need it?

**Comment by terrazoon** [comment]
The main thing is that in in app/delivery/send_to_providers.py, if the app is in research mode, the sms message doesn't get sent.  Instead, an sms response is simulated.

In theory, one could make some csv files and run everything in research mode, and test schedules and so forth without actually using up any of one's free allocation of sms messages or annoying users, but I'm hard pressed to think what the advantage would be.  We could not use it for load testing, because there is no load.  We could not use it to check error handling, because there wouldn't be any.

The only use case I can think of is perhaps a UI developer wants to test all the reports, so they make a csv list and go into research mode and send millions of fake sms messages.  But even in that instead, how useful will the reports be, since billing would not be correct, and provider details would not show any usage.

It doesn't seem to be a useful feature.

**Comment by terrazoon** [comment]
Yes, given that the original developers have deprecated it and we can't envision a good use case for it, I would recommend to just let it lie dormant.

**Comment by tdlowden** [comment]
👍  ty. 

closing
