### ISSUE TITLE
Content style guide

### ISSUE THREAD

**Issue by maomeara63** [GSA/notifications-admin#481]

**Comment by tdlowden** [comment]
https://docs.google.com/document/d/1XREFnitvK2MFdBu5cV8k6iKAEz5LAoHcMZExBQNYbag/edit#heading=h.gjdgxs

**Comment by em-herrick** [comment]
I have done a review and I am loving where the Content strategy deck is going, but I think it needs a bit more collaborative thought and review of existing research notes. I have added a bunch of (admittedly rambly) comments. 

Now that I am back from leave and conferencing, I am hoping to jump back into partner convo synthesis and come back to this with a more ground direction. 

While what we have is great for Notify, I'd also like to expand this deck to Notifications content. So would like to add a few more personas in and maybe another slide to delineate.

Happy to have this reassigned to me (or close the issue and I can move it forward outside of Github).

**Comment by em-herrick** [comment]
I think in order to close this issue, we should have a video discussion / crit. I'd like to share this more formally with Amy/Alex and the clearing. A lot of the terms Meghan defined here we have started using organically and it might be nice to do a group gut check on what we'd like to stop/continue. 

I've held co-working time on july 11 to do this with the wider team! @maomeara63 let's chat about how we might want to facilitate a discussion around terms

**Comment by tdlowden** [comment]
Sounds good on my end

**Comment by tdlowden** [comment]
Familiarization discussion is scheduled. Moving to close
