### ISSUE TITLE
Add a permissions check to the create user, create organizations, and create services views

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-admin#571]
As we shift toward getting ready for our official pilot, we also need to adjust some of our workflows so only US Notify admins are able to do the following:

- Create new user accounts outside of any service (e.g., the first user of a new org)
- Create new organizations

## Implementation Sketch and Acceptance Criteria

- [ ] Wrap the views associated with this functionality with the [`user_is_platform_admin`](https://github.com/GSA/notifications-admin/blob/main/app/utils/user.py#L36-L44) decorator (e.g., like the [`platform_admin` view](https://github.com/GSA/notifications-admin/blob/main/app/main/views/platform_admin.py#L41-L46) already is).
- [ ] Updated any tests to account for this change.

We could also approach this by removing the routes and shifting some of the logic/functionality to [custom Flask commands](https://flask.palletsprojects.com/en/2.3.x/cli/#custom-commands) that we run in the command line directly and/or as [one-off tasks](https://cloud.gov/docs/management/one-off-tasks/) within cloud.gov, but that's a lot of additional overhead that requires more planning.

## Security Considerations

- This will lock down some functionality currently accessible to public users and/or signed-in users.
- By modifying the permissions check on the associated views, this enables us to switch them back easily in the future when we're ready to enable more self-service functionality again.

**Comment by tdlowden** [comment]
@ccostino should we move this into "up Next"? i didn't realize the `user_is_platform_admin` decorator wasn't already across the site, and i think it plays into some other open issues we have, too

**Comment by ccostino** [comment]
@tdlowden if we ought to focus on this more than other things than yes, we can and should bring this in to "Up Next" - we can discuss more after a standup or our next sprint planning if need be.

As for creating new services, I see what you're saying - removing that from the list of things to do here!

**Comment by terrazoon** [comment]
To create a new organization, via the UI, you have to have access to the platform admin tab, hence you have to be a platform admin.   This works the same as the ability to 'go live' -- you can make yourself 'go live', but you have to be a platform admin to do so because it's on the platform admin tab, which is not visible to regular users.

**Comment by terrazoon** [comment]
To invite the first user to a new organization, you need to have the ability to view organizations, which is only available on the platform admin tab.  So is there any work to do here?  @tdlowden

I'll note also that the method add_organization() is currently decorated with user_is_platform_admin, and the method invite_org_user(), although it is only decorated with user_has_permissions(), can only invite user #1 to a new organization via the platform admin tab.  Otherwise, they can only invite team members and give them limited permissions.
