### ISSUE TITLE
Create new service does not work in `demo`

### ISSUE THREAD

**Issue by tdlowden** [GSA/notifications-admin#652]
When attempting to create a new service at /add-service in the demo env, there appears to be a bug, where you name a service, click the button, and nothing happens. But, in staging, you can create a service just fine. This makes me think that it's just a matter of doing a push from staging to demo to sync them. But what catches my eye is that in staging, there remains the radio to choose "Federal", "State", or "Other', while in the demo env, those option are not there. and that does not make sense to me, because I do not think we removed those options and then re-inserted them at any time. 

![Image](https://user-images.githubusercontent.com/6556888/255975834-e55554d0-b409-450e-8d2f-34ec751e654a.png)

**Comment by tdlowden** [comment]
This seems to have resolved in the recent push. Closing.

**Comment by tdlowden** [comment]
Not sure what's going on, but this is back

**Comment by terrazoon** [comment]
I was able to create a service on demo on 8/21

**Comment by tdlowden** [comment]
In the UI? so strange. I just tried again. When I name the service and press `Add Service`, nothing happens. And I know Cathy had experienced the same. I did a hard refresh with cache clear and experienced the same. 

I don't know what would cause some of us to be able to replicate, but not others.

<img width="827" alt="image" src="https://github.com/GSA/notifications-admin/assets/6556888/0bc8d939-3743-48c8-9473-6854ba259a23">

**Comment by terrazoon** [comment]
Yes, in the UI.  I was using Chrome.  We might want to keep track of what browsers were used if it's really a flaky UI issue.  I added a k1 service after creating a user on demo.

What's weird is that it worked for you, once.

**Comment by terrazoon** [comment]
Can you open the page in Chrome, reproduce and use Developer Tools to see if there is an error of some kind?  (Upper right corner -> More Tools -> Developer Tools).

This is what I see on demo when it is working normally:


<img width="1728" alt="Screenshot 2023-08-21 at 9 15 59 AM" src="https://github.com/GSA/notifications-admin/assets/26859290/5846007a-2b40-47ad-bae6-ee22638a4b11">

**Comment by tdlowden** [comment]
Console: 
<img width="701" alt="image" src="https://github.com/GSA/notifications-admin/assets/6556888/dd598734-641b-4c2e-bb49-a7b3d661f732">

**Comment by terrazoon** [comment]
Steven thinks this might be a Zscaler issue, the evidence being that Tim, Carlo, and Steven can reproduce it and Ken can't.  If you have access to a non-Zscaler machine, you could try to access the demo and repro to help confirm this.

**Comment by tdlowden** [comment]
That's the same behavior I see, as well. 

So, @terrazoon @stvnrlly I think we can rule out Zscaler as the culprit.

**Comment by ccostino** [comment]
@maomeara63 and @tdlowden, if you open the site in an incognito browser window (if you need help just let me know!), do you also experience this issue?

I just tried to do this on the demo site myself in a normal browser window (which has history, cookies, etc.) and an incognito window and experienced the issue in both as well.  I'm not seeing any indication of what's wrong in the browser, nor am I see any errors showing up in the logs (I did see an unrelated one in the API, `Celery task check_sms_delivery_receipt (queue: check-sms_tasks) failed`), so this is a thornier one to debug for sure.  Especially since it's not happening consistently across environments, either.

Is there a possibility our permissions are a little messed up in demo, and we don't actually have access to create a service but we're just not seeing any error output or anything?

**Comment by maomeara63** [comment]
@ccostino Even in incognito I experience this problem.
