### ISSUE TITLE
Add X-Frame-Options header

### ISSUE THREAD

**Issue by stvnrlly** [GSA/notifications-admin#944]
This header lets other sites know that they can't embed our site in a frame. Should be automatically added by `flask-talisman` (see https://github.com/GoogleCloudPlatform/flask-talisman), so it may just be about configuring that.

**Comment by anagradova** [comment]
This was the output of the crawler run against the E2E test configuration for X-Frame-Options header. These are all the links it could traverse off the home page. 

[
{"page": "http://localhost:6012/support", "header": "deny"},
{"page": "http://localhost:6012/user-profile", "header": "deny"},
{"page": "http://localhost:6012/features", "header": "deny"},
{"page": "http://localhost:6012/using-notify/get-started", "header": "deny"},
{"page": "http://localhost:6012/accounts", "header": "deny"},
{"page": "http://localhost:6012/services/339000e1-8df8-482d-84c5-1a90741735ac/service-settings", "header": "deny"},
{"page": "http://localhost:6012/services/339000e1-8df8-482d-84c5-1a90741735ac/usage", "header": "deny"},
{"page": "http://localhost:6012/services/339000e1-8df8-482d-84c5-1a90741735ac#main-content", "header": "deny"},
{"page": "http://localhost:6012/services/339000e1-8df8-482d-84c5-1a90741735ac/templates", "header": "deny"},
{"page": "http://localhost:6012/services/339000e1-8df8-482d-84c5-1a90741735ac/notifications/sms?status=sending,delivered,failed", "header": "deny"}
]

**Comment by ccostino** [comment]
It also turns out that this was a reported false positive by the security scans.  We've notified our ISSO of our findings with this and why the missing header was flagged, and they are following up with the security team to resolve the issue and have the finding marked as a false positive.

Thanks for digging into this and helping confirm it's not an issue on our side, @anagradova!
